// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMIyVn8r_KZEfTsO2_Ie19rK3Ttpzm5TY',
    appId: '1:665991990053:web:33931165eb193bd4c968cc',
    messagingSenderId: '665991990053',
    projectId: 'event-app-d9a73',
    authDomain: 'event-app-d9a73.firebaseapp.com',
    storageBucket: 'event-app-d9a73.firebasestorage.app',
    measurementId: 'G-86930RXXEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGmnoVDPVYfgoMHTLnc1KCtvxmOKbvPw8',
    appId: '1:665991990053:android:3e1f34322e18eb39c968cc',
    messagingSenderId: '665991990053',
    projectId: 'event-app-d9a73',
    storageBucket: 'event-app-d9a73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxug3i0hw_8Oonahk8FYw9DyrRx3DqNo',
    appId: '1:665991990053:ios:dae5e0f1fdbb5f21c968cc',
    messagingSenderId: '665991990053',
    projectId: 'event-app-d9a73',
    storageBucket: 'event-app-d9a73.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcxug3i0hw_8Oonahk8FYw9DyrRx3DqNo',
    appId: '1:665991990053:ios:dae5e0f1fdbb5f21c968cc',
    messagingSenderId: '665991990053',
    projectId: 'event-app-d9a73',
    storageBucket: 'event-app-d9a73.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMIyVn8r_KZEfTsO2_Ie19rK3Ttpzm5TY',
    appId: '1:665991990053:web:0add4cc8cfe20780c968cc',
    messagingSenderId: '665991990053',
    projectId: 'event-app-d9a73',
    authDomain: 'event-app-d9a73.firebaseapp.com',
    storageBucket: 'event-app-d9a73.firebasestorage.app',
    measurementId: 'G-3SJ9W0VXX2',
  );
}
